Update build-kernel

diff --git a/build-kernel b/build-kernel
--- a/build-kernel
+++ b/build-kernel
@@ -6,61 +6,145 @@
 ##  Updated: 03.12.24
 ##  Script version: 2.8
 
-clear
+show_help() {
+    echo "Usage: $(basename "$0") [options]"
+    echo "Options:"
+    echo "  -h, --help                  Show this help message."
+    echo "  -v, --version VERSION       Set a custom version number of the WSL2 kernel to install."
+    echo "  -o, --output-directory DIRECTORY  Specify where the vmlinux file should be placed after build."
+}
 
-if [ "${EUID}" -ne '0' ]; then
-    printf "%s\n\n" 'You must run this script with root/sudo.'
+version_specified=false
+specific_version=""
+output_directory=""
+version_type=""
+
+while [[ $# -gt 0 ]]; do
+    case $1 in
+        -h|--help)
+            show_help
+            exit 0
+            ;;
+        -v|--version)
+            version_specified=true
+            specific_version="linux-msft-wsl-$2"
+            shift # past argument
+            shift # past value
+            ;;
+        -o|--output-directory)
+            output_directory=$2
+            shift # past argument
+            shift # past value
+            ;;
+        *)
+            shift # past argument
+            ;;
+    esac
+done
+
+if [ "$EUID" -ne 0 ]; then
+    echo "You must run this script with root/sudo."
     exit 1
 fi
 
-# Define the program name, an output directory, and error log file
-program_name='wsl2-kernel'
-script_dir="$PWD"
-cwd="/tmp/$program_name-build-script"
-error_log="/tmp/error.log"
+# Prompting the user for input if no version specified
+if ! $version_specified; then
+    while true; do
+        echo "Choose the WSL2 kernel version to download and install:"
+        echo
+        echo "1. Linux series 6 kernel"
+        echo "2. Linux series 5 kernel"
+        echo "3. Specific version"
+        echo "4. Exit"
+        echo
+        read -p "Enter your choice (1-4): " choice
 
-# Create and change to the build directory
+        case $choice in
+            1)
+                version_type="6"
+                break
+                ;;
+            2)
+                version_type="5"
+                break
+                ;;
+            3)
+                read -p "Enter the version numbers (e.g., 5.15.90.1): " user_input
+                specific_version="linux-msft-wsl-$user_input"
+                version_specified=true
+                break
+                ;;
+            4)
+                echo "Exiting the script."
+                exit 0
+                ;;
+            *)
+                echo "Invalid choice. Please try again."
+                ;;
+        esac
+    done
+fi
+
+# Ensure the directory for 'vmlinux' is prepared.
+if [ -z "$output_directory" ]; then
+    script_dir="$PWD" # Use current directory if no output directory is specified
+else
+    script_dir="$output_directory"
+    mkdir -p "$script_dir" # Create output directory if it does not exist
+fi
+
+master_dir="/tmp/wsl2-build-script" # Master parent directory
+cwd="$master_dir/wsl2-kernel-build-script"
+error_log="$master_dir/error.log"
+
+# Create the master parent directory and the build directory within it
 mkdir -p "$cwd"
 cd "$cwd" || exit 1
 
 # Set compiler optimizations
-CC='gcc'
-CXX='g++'
-CFLAGS='-g -O3 -march=native'
+CC="gcc"
+CXX="g++"
+CFLAGS="-g -O3 -march=native"
 CXXFLAGS="$CFLAGS"
 
 export CC CXX CFLAGS CXXFLAGS
 
-install_required_packages() {
-    local missing_packages pkg packages
+announce_options() {
+    # Announce options after all inputs have been processed
+    echo "Final script configuration:"
+    echo "Specific version specified: $version_specified"
+    if $version_specified; then
+        echo "Specific version: $specific_version"
+    else
+        echo "Version: Using the latest available version"
+    fi
+    echo "Output directory: ${output_directory:-"Default directory ($PWD)"}"
+}
 
-    pkgs=(
-             aria2 bc bison build-essential cmake curl debootstrap dwarves flex g++
-             g++-s390x-linux-gnu gcc gcc-s390x-linux-gnu gdb-multiarch git libcap-dev
-             libelf-dev libelf-dev libncurses-dev libncurses5 libncursesw5 libncursesw5-dev
-             libssl-dev make pkg-config python3 qemu-system-misc qemu-utils rsync wget
+install_required_packages() {
+    local missing_packages=""
+    local pkgs=(
+        aria2 bc bison build-essential cmake curl debootstrap dwarves flex g++
+        g++-s390x-linux-gnu gcc gcc-s390x-linux-gnu gdb-multiarch git libcap-dev
+        libelf-dev libncurses-dev libncurses5 libncursesw5 libncursesw5-dev
+        libssl-dev make pkg-config python3 qemu-system-misc qemu-utils rsync wget
     )
 
-    # Initialize an empty string for missing packages
-    missing_packages=""
-
-    # Loop through the array
-    for pkg in "${pkgs[@]}"
-    do
-        # Check if the package is installed using dpkg-query
+    for pkg in "${pkgs[@]}"; do
         if ! dpkg-query -W -f='${Status}' "$pkg" 2>/dev/null | grep -q "ok installed"; then
-            # If not installed, add it to the missing packages list
             missing_packages+="$pkg "
         fi
     done
 
-    # Check if there are any missing packages
     if [ -n "$missing_packages" ]; then
-        # Install missing packages
-        printf "\n%s\n\n" "Installing missing packages: $missing_packages"
-        sudo apt -y install $missing_packages
+        echo
+        echo "Installing missing packages: $missing_packages"
+        echo
+        sudo apt-get -y install $missing_packages
     else
-        printf "%s\n\n" "All packages are already installed."
+        echo
+        echo "All APT packages are already installed."
+        echo
     fi
 }
 
@@ -74,10 +158,10 @@ download_file() {
     fi
 
     if command -v wget &> /dev/null; then
-        echo 'Downloading with wget...'
+        echo "Downloading with wget..."
         wget --show-progress -cqO "$output_file" "$url"
     else
-        echo 'wget is not installed. Please install wget.'
+        echo "wget is not installed. Please install wget."
         exit 1
     fi
 }
@@ -90,13 +174,11 @@ get_latest_release_version() {
     curl -s "$url" | grep -oP "$pattern" | head -1
 }
 
-# Function to build the kernel without a progress bar
 build_kernel_without_progress() {
-    printf "%s\n%s\n" \
-       'Installing the WSL2 Kernel' \
-       '========================================='
-    if ! echo 'yes' | make "-j$(nproc --all)" KCONFIG_CONFIG='Microsoft/config-wsl' 2>>"$error_log"; then
-        printf "%s\n" "Build process terminated with errors. Please check the error log below:"
+    echo "Installing the WSL2 Kernel"
+    echo "========================================="
+    if ! echo "yes" | make "-j$(nproc --all)" KCONFIG_CONFIG="Microsoft/config-wsl" 2>>"$error_log"; then
+        echo "Build process terminated with errors. Please check the error log below:"
         cat "$error_log"
         return 1
     fi
@@ -105,89 +187,74 @@ build_kernel_without_progress() {
 
 install_kernel() {
     clear
-    printf "%s\n\n" "Successfully downloaded the source code file \"$latest_release_tag\""
+    announce_options
     install_required_packages
-    version=$(get_latest_release_version "$version_type")
+
+    if [ -n "$specific_version" ]; then
+        version="$specific_version"
+    else
+        version=$(get_latest_release_version "$version_type")
+    fi
+
+    echo "Downloading kernel version $specific_version..."
+
     if [ -z "$version" ]; then
-        printf "%s\n\n" 'Failed to find the latest version. Exiting.'
+        echo "Failed to find the latest version. Exiting."
+        echo
         exit 1
     fi
 
-    tar_file="/tmp/$program_name-$version.tar.gz"
+    echo "Successfully downloaded the source code file \"$version\""
+    echo
+
+    tar_file="$master_dir/$program_name-$version.tar.gz"
     download_url="https://github.com/microsoft/WSL2-Linux-Kernel/archive/refs/tags/$version.tar.gz"
 
-    # Check if the downloaded file already exists
-    if [ -f "$tar_file" ]; then
-        printf "%s\n\n" "Using the existing downloaded file: $tar_file"
-    else
-        download_file "$download_url" "$tar_file"
-    fi
+    download_file "$download_url" "$tar_file"
 
-    extract_dir="/tmp/$program_name-$version"
+    extract_dir="$master_dir/$program_name-$version"
     [ -d "$extract_dir" ] && rm -rf "$extract_dir"
 
     mkdir -p "$extract_dir"
     if ! tar -zxf "$tar_file" -C "$extract_dir" --strip-components 1; then
-        printf "%s\n\n" 'Failed to extract the archive. Exiting.'
+        echo "Failed to extract the archive. Deleting the corrupt archive."
+        rm -f "$tar_file"
+        echo
+        echo "The archive file has been deleted due to extraction failure."
+        echo "Please run the script again to fix the issue."
         exit 1
     fi
 
     cd "$extract_dir" || exit 1
-    printf "%s\n\n" 'Building the kernel...'
+    echo "Building the kernel..."
+    echo
     if ! build_kernel_without_progress; then
         rm -rf "$extract_dir"
-        printf "%s\n" "Error log:"
+        echo "Error log:"
         cat "$error_log"
+        echo "Kernel build failed. Please check the error log above for more information."
         return 1
-    fi
-
-    # Check for vmlinux file and move it to $PWD
-    find_vmlinux="$(find $PWD -type f -name 'vmlinux' | head -n1)"
-    if [ -f "$find_vmlinux" ]; then
-        mv "$find_vmlinux" "$script_dir/vmlinux"
-        printf "%s\n\n" 'Kernel build successful. vmlinux moved to the script directory.'
-
-        read -p "Do you want to delete the build directory? (y/n): " user_choice
-        if [ "$user_choice" = "y" ]; then
-            rm -fr "$cwd"
-            printf "%s\n\n" 'Build directory cleaned up.'
-        else
-            printf "%s\n\n" 'Build directory retained as per user choice.'
-        fi
     else
-        printf "%s\n" 'Error: vmlinux file not found. Please check the build process.'
-        return 1
+        find_vmlinux="$(find $PWD -type f -name 'vmlinux' | head -n1)"
+        if [ -f "$find_vmlinux" ]; then
+            mv "$find_vmlinux" "$script_dir/vmlinux"
+            echo "Kernel build successful. vmlinux moved to the specified output directory: $script_dir"
+            echo
+
+            read -p "Do you want to delete the build directory? (y/n): " user_choice
+            if [ "$user_choice" = "y" ]; then
+                rm -fr "$master_dir"
+                echo "Build directory cleaned up."
+                echo
+            else
+                echo "Build directory retained as per user choice."
+                echo
+            fi
+        else
+            echo "Error: vmlinux file not found. Please check the build process."
+            return 1
+        fi
     fi
 }
 
-# Main script execution
-while true; do
-    printf "%s\n" "Choose the WSL2 kernel version to download and install:"
-    printf "%s\n" "1. Linux series 6 kernel"
-    printf "%s\n" "2. Linux series 5 kernel"
-    printf "%s\n" "3. Exit"
-    read -p "Enter your choice (1-3): " choice
-
-    case $choice in
-        1)
-            version_type="6"
-            break
-            ;;
-        2)
-            version_type="5"
-            break
-            ;;
-        3)
-            printf "%s\n" "Exiting the script."
-            exit 0
-            ;;
-        *)
-            printf "%s\n" "Invalid choice. Please try again."
-            ;;
-    esac
-done
-
-get_latest_release_version "$version_type"
-if ! install_kernel; then
-    printf "%s\n" "Kernel build failed. Please check the error log above for more information."
-fi
+install_kernel
