Update build-kernel

diff --git a/build-kernel b/build-kernel
--- a/build-kernel
+++ b/build-kernel
@@ -3,8 +3,8 @@
 
 ##  GitHub Script: https://github.com/slyfox1186/wsl2-kernel-build-script/blob/main/build-kernel
 ##  Purpose: Build Official WSL2 Kernels
-##  Updated: 01.09.24
-##  Script version: 2.5
+##  Updated: 01.13.24
+##  Script version: 2.6
 
 clear
 
@@ -35,7 +35,7 @@ install_required_packages()
 {
     local missing_packages pkg packages
 
-    packages=(
+    pkgs=(
              aria2 bc bison build-essential cmake curl debootstrap dwarves flex g++
              g++-s390x-linux-gnu gcc gcc-s390x-linux-gnu gdb-multiarch git libcap-dev
              libelf-dev libelf-dev libncurses-dev libncurses5 libncursesw5 libncursesw5-dev
@@ -80,7 +80,7 @@ download_file()
         aria2c -x 16 -s 16 -o "$output_file" "$url"
     elif command -v wget &> /dev/null; then
         echo 'Downloading with wget...'
-        wget --show-progress -cqO "$output_file" "$url"
+        wget -cqO "$output_file" "$url"
     elif command -v curl &> /dev/null; then
         echo 'Downloading with curl...'
         curl -L "$url" -o "$output_file"
@@ -96,42 +96,18 @@ get_latest_release_version()
     echo "$latest_release_tag"
 }
 
-# Function to draw the progress bar
-draw_progress_bar()
-{
-    local progress=$1
-    local total=$2
-    local filled=$((progress * 20 / total))
-    local empty=$((20 - filled))
-    printf "\r["
-    printf "%0.s#" $(seq 1 $filled)
-    printf "%0.s-" $(seq 1 $empty)
-    printf "] %d%% (%d/%d)" $((progress * 100 / total)) $progress $total
-}
-
-# Function to build the kernel with a progress bar
-build_kernel_with_progress()
-{
-    local total_steps=$(grep -c '^' Microsoft/config-wsl) # Estimate total steps
-    local current_step=0
-
-    # Start building the kernel
+# Function to build the kernel without a progress bar
+build_kernel_without_progress() {
     printf "%s\n%s\n" \
-        'Installing the WSL2 Kernel' \
-        '========================================='
-    yes '' | make "-j$(nproc --all)" KCONFIG_CONFIG='Microsoft/config-wsl' 2>>"$error_log" | while read -r line; do
-        ((current_step++))
-        draw_progress_bar $current_step $total_steps
-    done
-    printf "\n"
-
-    # Check if build was successful
-    if [ $? -ne 0 ]; then
+       'Installing the WSL2 Kernel' \
+       '========================================='
+    if ! echo 'yes' | make "-j$(nproc --all)" KCONFIG_CONFIG='Microsoft/config-wsl' 2>>"$error_log"; then
         printf "%s\n" "Build process terminated with errors. Please check the error log at $error_log."
         return 1
     fi
     return 0
 }
+
 install_kernel()
 {
     clear
@@ -159,7 +135,7 @@ install_kernel()
 
     cd "$extract_dir" || exit 1
     printf "%s\n\n" 'Building the kernel...'
-    if ! build_kernel_with_progress; then
+    if ! build_kernel_without_progress; then
         return 1
     fi
 
